// <copyright file="AuctionListing.Generated.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by a roslyn code generator.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace MUnique.OpenMU.Persistence.EntityFramework.Model;

using System.ComponentModel.DataAnnotations.Schema;
using MUnique.OpenMU.Persistence;

/// <summary>
/// The Entity Framework Core implementation of <see cref="MUnique.OpenMU.DataModel.Entities.AuctionListing"/>.
/// </summary>
[Table(nameof(AuctionListing), Schema = SchemaNames.AccountData)]
internal partial class AuctionListing : MUnique.OpenMU.DataModel.Entities.AuctionListing, IIdentifiable
{
    
    
    /// <summary>
    /// Gets or sets the identifier of this instance.
    /// </summary>
    public Guid Id { get; set; }
    
    /// <summary>
    /// Gets or sets the identifier of <see cref="EscrowItem"/>.
    /// </summary>
    public Guid? EscrowItemId { get; set; }

    /// <summary>
    /// Gets the raw object of <see cref="EscrowItem" />.
    /// </summary>
    [ForeignKey(nameof(EscrowItemId))]
    public Item RawEscrowItem
    {
        get => base.EscrowItem as Item;
        set => base.EscrowItem = value;
    }

    /// <inheritdoc/>
    [NotMapped]
    public override MUnique.OpenMU.DataModel.Entities.Item EscrowItem
    {
        get => base.EscrowItem;set
        {
            base.EscrowItem = value;
            this.EscrowItemId = this.RawEscrowItem?.Id;
        }
    }


    /// <inheritdoc/>
    public override bool Equals(object obj)
    {
        var baseObject = obj as IIdentifiable;
        if (baseObject != null)
        {
            return baseObject.Id == this.Id;
        }

        return base.Equals(obj);
    }

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        return this.Id.GetHashCode();
    }

    
}
