// <copyright file="WCoinTransaction.Generated.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by a roslyn code generator.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace MUnique.OpenMU.Persistence.EntityFramework.Model;

using System.ComponentModel.DataAnnotations.Schema;
using MUnique.OpenMU.Persistence;

/// <summary>
/// The Entity Framework Core implementation of <see cref="MUnique.OpenMU.DataModel.Entities.WCoinTransaction"/>.
/// </summary>
[Table(nameof(WCoinTransaction), Schema = SchemaNames.AccountData)]
internal partial class WCoinTransaction : MUnique.OpenMU.DataModel.Entities.WCoinTransaction, IIdentifiable
{
    
    
    /// <summary>
    /// Gets or sets the identifier of this instance.
    /// </summary>
    public Guid Id { get; set; }
    
    /// <summary>
    /// Gets or sets the identifier of <see cref="Account"/>.
    /// </summary>
    public Guid? AccountId { get; set; }

    /// <summary>
    /// Gets the raw object of <see cref="Account" />.
    /// </summary>
    [ForeignKey(nameof(AccountId))]
    public Account RawAccount
    {
        get => base.Account as Account;
        set => base.Account = value;
    }

    /// <inheritdoc/>
    [NotMapped]
    public override MUnique.OpenMU.DataModel.Entities.Account Account
    {
        get => base.Account;set
        {
            base.Account = value;
            this.AccountId = this.RawAccount?.Id;
        }
    }


    /// <inheritdoc/>
    public override bool Equals(object obj)
    {
        var baseObject = obj as IIdentifiable;
        if (baseObject != null)
        {
            return baseObject.Id == this.Id;
        }

        return base.Equals(obj);
    }

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        return this.Id.GetHashCode();
    }

    
}
