// <copyright file="AuctionListing.Generated.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by a roslyn code generator.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace MUnique.OpenMU.Persistence.BasicModel;

using MUnique.OpenMU.Persistence.Json;

/// <summary>
/// A plain implementation of <see cref="AuctionListing"/>.
/// </summary>
public partial class AuctionListing : MUnique.OpenMU.DataModel.Entities.AuctionListing, IIdentifiable, IConvertibleTo<AuctionListing>
{
    
    /// <summary>
    /// Gets or sets the identifier of this instance.
    /// </summary>
    public Guid Id { get; set; }
    
    /// <summary>
    /// Gets the raw object of <see cref="EscrowItem" />.
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("escrowItem")]
    public Item RawEscrowItem
    {
        get => base.EscrowItem as Item;
        set => base.EscrowItem = value;
    }

    /// <inheritdoc/>
    [System.Text.Json.Serialization.JsonIgnore]
    public override MUnique.OpenMU.DataModel.Entities.Item EscrowItem
    {
        get => base.EscrowItem;
        set => base.EscrowItem = value;
    }


    /// <inheritdoc/>
    public override bool Equals(object obj)
    {
        var baseObject = obj as IIdentifiable;
        if (baseObject != null)
        {
            return baseObject.Id == this.Id;
        }

        return base.Equals(obj);
    }

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        return this.Id.GetHashCode();
    }

    /// <inheritdoc/>
    public AuctionListing Convert() => this;
}
